### ISSUE TITLE
Having several binaries binding to the same src

### ISSUE THREAD

**Issue by mauriciojxs** [hilkoc/vbaDeveloper#10]
Hello,

Nice work with the tool, it's really helping me.

I was wondering how (if) you deal with having more than one Excel binary (.xlsm) linked to the same src files? I'll explain my case.
I have a couple of files that will be using the same libraries. I think of put them on the same root folder, and when I export/import the code, they would both point to the same subdirectory (that would be `./src/` instead of `./src/filename.xlsm/`)

Thanks,
Mauricio

**Comment by hilkoc** [comment]
The code can easily be modified to do as you suggest. However, this is not a recommended way for modules to share code. Eventually all the excel binaries will end up with duplicate copies of the same code.
It's better to move the code to a separate (new) addin and let both excel books reference that addin.
