### ISSUE TITLE
vbaDeveloper should use itself

### ISSUE THREAD

**Issue by ckuhn203** [hilkoc/vbaDeveloper#13]
The purpose of the project is to help get plain text source code files into source control. Shouldn't there be plain text files in this repo? =;)-

**Comment by Merlin2001** [comment]
Hi ckuhn!

I first thought the folders (e.g. src/vbaDeveloper.xlam) were xlam-files, too.
But if you actually click on them, you get directly to the source files (.bas and .cls files).
Maybe you can close this issue :)

Hth
Merlin
