### ISSUE TITLE
Saving the vbaDeveloper.xlam file - Excel 2013

### ISSUE THREAD

**Issue by pmesgari** [hilkoc/vbaDeveloper#23]
This tool sounds very promising, but its installation has been a nightmare so far. I am using Excel 2013 and if I try to save the file with the name vbaDeveloper.xlam leaving the Sav as type as it is, I get the "To continue saving as macro-free workbook, click Yes", If I click Yes then the file can not be opened. If I click No then I am stuck. What is the solution?

**Comment by hilkoc** [comment]
This addin has never been tested with excel 2013. Is it possible to create a plain empty .xlam file in excel 2013? Try doing that first and then import the vba code.

**Comment by abbood** [comment]
@pmesgari any news?

**Comment by jeichas** [comment]
I am having this problem with Excel 2016.  I'll try the suggestion of @hilkoc and report back.

**Comment by jeichas** [comment]
@hilkoc suggestion does work. Newer versions of excel must get confused when they start as .xlsm and then are saved to .xlam later.
