### ISSUE TITLE
subscript out of range error when running testImport

### ISSUE THREAD

**Issue by abbood** [hilkoc/vbaDeveloper#24]
I'm running this on Excel 2016 (as part of the office 365)

I followed the detailed instructions.. but when I put the cursor on the `testImport` function and ran f5.. I got this error:

![image](https://cloud.githubusercontent.com/assets/774379/20459517/2a02d804-ae79-11e6-9bf9-6e27487c39b0.png)

any ideas?

**Comment by brochuJP** [comment]
I had the same problem. If you select vbaProject (vbaDeveloper.xlam) in the Project window, and after you go in the Properties window, you must see the name "VbaDeveloper". In other therms the Property Name of you VBA project must be equal to the variable proj_name that is declare in testImport.

**Comment by hilkoc** [comment]
Indeed as brochuJP said, don't skip step 3 in the installation steps, to rename the vba project to vbaDeveloper.
