### ISSUE TITLE
Sub Format hides excel's Format function

### ISSUE THREAD

**Issue by bitterjug** [hilkoc/vbaDeveloper#25]
Formatter module contains `public sub format()`.
Excel has a built-in function called `Format`.
if I add a reference to your project (so I can call `exportVbProject`) I my calls to the latter are mistaken for calls to the former which causes errors.

**Comment by hilkoc** [comment]
That is a good point. The format function should be renamed. Any suggestions for a short and clear name? Maybe 'FormatVba()'.

For now, just use the fully qualified name i.e.  ModuleName.FunctionName() to call the function. That will always work as expected.

**Comment by gkuenzli** [comment]
What about FormatActiveCodePane ?

Certainly not short by quite clear.

**Comment by yarick123** [comment]
please look at the patch https://github.com/hilkoc/vbaDeveloper/pull/43 above
