### ISSUE TITLE
Multiple projects with the same name causes confusion

### ISSUE THREAD

**Issue by gberl001** [hilkoc/vbaDeveloper#3]
I'm not one who typically renames the project as I'm fine just using the default name.  However, I found that when I tried to use this the addin kept exporting my other addin(s).  The problem is that the addins I use (including some MS ones), as well as my projects all have the same name (VBAProject).

To fix this, I will simply change my project names but if I get ambitious I may alter the code and suggest a pull request.  I think this could easily be fixed by utilizing the project ID rather than the name.  The ID is unique and from the ID you can get the project name as well as the workbook name etc.

![image](https://cloud.githubusercontent.com/assets/4296563/5839059/960952be-a159-11e4-828e-ebeb94341bd7.png)

**Comment by NealHumphrey** [comment]
This would be useful if you do decide to go for it! I haven't run into the issue yet but probably will.

**Comment by hilkoc** [comment]
A good idea. Of course the tool should be able to handle duplicate project names correctly. I'd be happy to take a pull request for this, or might make the change myself if I can find the time for it.

**Comment by ckuhn203** [comment]
I've run into this issue in my own project. If anyone comes up with a sensible solution please @ ping me. P
