### ISSUE TITLE
Logger missing attribution required by CC-BY-SA license

### ISSUE THREAD

**Issue by retailcoder** [hilkoc/vbaDeveloper#36]
While I don't particularly care whether my code is taken and transformed beyond recognition, it would have been nice to include a little comment *somewhere*, acknowledging the original work this code is clearly based on, which was published on Code Review Stack Exchange 2014-09-28 under a CC-BY-SA license (i.e. attribution required) and can be found [here](https://codereview.stackexchange.com/q/64109).

Cheers!

**Comment by hilkoc** [comment]
The VbaLogger was developed and completed long before your post. It's just that because of the infrequent commits it was committed later. The author has never looked at that code at all. This is all original work.
