### ISSUE TITLE
How to remove vbaDeveloper from a workbook?

### ISSUE THREAD

**Issue by hereticbill** [hilkoc/vbaDeveloper#42]
vbaDeveloper is very useful when I'm doing development, but at some point I want to deliver the product (workbook) to a non-developer recipient without the additional baggage of the vbaDeveloper plug-in. Surely I'm not the first to want this? But in the VBE it's not possible to delete the vbaDeveloper project ("Remove" option is grayed out), nor is it possible to remove it with a VBA program or command (VBProjects collection does not have a Remove/Delete/Clear method).

Anyone that can help with this? Have you successfully removed vbaDeveloper from a workbook?

**Comment by hilkoc** [comment]
Hi @hereticbill 
Not sure what you mean by 'remove', but I think you can give this a try:
In the workbook you plan to deliver, go to the VBA macro editor, then in the menu find 'tools' -> 'references'  and untick the box in front of the VbaDeveloper addin.

**Comment by hereticbill** [comment]
Ok, so that led me down the right path (even though I'd done that before). Unchecking the reference (or removing it from the References collection with VB) does not remove vbaDeveloper. But: if I save it afterwards, close Excel, then re-open the deliverable workbook, it's gone. Thanks! This will save me a lot of time. Also: thanks for making vbaDeveloper, it's very useful. :-)

**Comment by hilkoc** [comment]
Great! I'm happy that helped.
