### ISSUE TITLE
wrong indentation after code formatting

### ISSUE THREAD

**Issue by yarick123** [hilkoc/vbaDeveloper#45]
code like
```vba
    Do Until (rs.State = adStateOpen): Set rs = rs.NextRecordset: Loop
    If (rs.Fields.count < 1 Or rs.Fields(0).Name <> "VERSION") Then
        Err.Raise Number:=vbObjectError + 500, Description:="Cannot read server side API version number"
    End If
```
is formatted to
```vba
    Do Until (rs.State = adStateOpen): Set rs = rs.NextRecordset: Loop
        If (rs.Fields.count < 1 Or rs.Fields(0).Name <> "VERSION") Then
            Err.Raise Number:=vbObjectError + 500, Description:="Cannot read server side API version number"
        End If
```
As a solution I propose the patch https://github.com/hilkoc/vbaDeveloper/pull/44. It introduces a constant SIMPLIFIED_FORMAT, initialized with False by default. If it is set to True, the code formatting will be reduced just to trimming trailing spaces of each code line.

**Comment by hilkoc** [comment]
Why would you think this is an issue? The if-statement is clearly inside the loop. Therefore it should be indented.
