### ISSUE TITLE
why is frm file adding a blank line

### ISSUE THREAD

**Issue by jellisjo** [hilkoc/vbaDeveloper#51]
is there a way to prevent the addition of the blank line?

![image](https://user-images.githubusercontent.com/48917190/103461619-02990c00-4cdd-11eb-83cc-99e990173828.png)

**Comment by hilkoc** [comment]
To do that you'd have to write additional code to modify the frm file after it has been exported.
I don't see any point in doing that and it might break the importing of the file.
