### ISSUE TITLE
VBA- Outlook follow up flag seting

### ISSUE THREAD

**Issue by Saasvba** [hilkoc/vbaDeveloper#53]
We have a shared email, we are under using follow up flag function to sort email,how can I use a macro to automatic mark email on follow up flag column with some logic。

**Comment by brochuJP** [comment]
I suggest I have a look at www.autoprocess.dev they have tools for Outlook automation. When an email is received in your mailbox that match a specific pattern this can trigger an automation.

**Comment by brochuJP** [comment]
Create an email reception rule that will trigger a VBA script. In the VBA script use the email as an input of your function. In the fonction assign a flag with your preferred color.
