### ISSUE TITLE
Variable not defined

### ISSUE THREAD

**Issue by RaAlMer** [hilkoc/vbaDeveloper#57]
When I get to step 9:
9. Let vbaDeveloper import its own code: Put the cursor in the function 'testImport' and press F5

It throws an error in Build as it says it is not defined. I cannot find the solution to this ...

Thank you for your answer!

![7](https://user-images.githubusercontent.com/67586098/126542726-33c22b7f-8309-4d3a-a940-c790b501bfc7.png)

**Comment by brochuJP** [comment]
It looks like the declaration of your variables are activated. You can change that in the settings.

**Comment by brochuJP** [comment]
Option Explicit

**Comment by RaAlMer** [comment]
Thanks, I'll check it. I didn't know some of the variables weren't defined in the code so that the Option Explicit throws errors.
