### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by swarren** [hilkoc/vbaDeveloper#9]
There's no license specified in this project anywhere. Can I take the code under the MIT license? It'd be useful if you added a LICENSE file and/or license headers to the individual source files. Thanks!

**Comment by PetLahev** [comment]
Hi @swarren , feel free to take any source code you want, I'll try to add the license somewhere. First I need to figure out, what, how and where :)

**Comment by swarren** [comment]
You mentioned in email you needed to work out what to do to add a license file.

You'd add a comment containing your copyright notice and some license text. to the top of every file in the project.

For short licenses, you can put the entire license in each file. http://opensource.org/licenses/MIT contains the text you'd add for the MIT license for example.

For longer licenses, you'd typically put a LICENSE.txt or COPYING file at the top-level of the project containing the license text, and add a short header to each file with your copyright notice and an indication that the file was under a particular license. http://opensource.org/licenses/GPL-2.0 contains example license text for a "long" license, and also a section "How to Apply These Terms to Your New Programs" which contains the text you'd put into each file.

Hope this helps.

**Comment by swarren** [comment]
On 07/21/2015 02:23 PM, PetLahev wrote:
> Hi @swarren <https://github.com/swarren> , feel free to take any source
> code you want, I'll try to add the license somewhere. First I need to
> figure out, what, how and where :)

When you say "take any source code you want", can I assume that the code 
is MIT licensed (which is what I hoped in the message you responded to), 
or might you decide to use a different license?

Thanks!

**Comment by juanwinsor** [comment]
hello @hilkoc I am looking for clarification on the license for the the vbaDeveloper code base, I couldn't find another way to contact you.  I don't need a license or permission for the logger.

**Comment by hilkoc** [comment]
Thanks everyone for suggesting to add a license. The entire project is now under MIT license.
